create table if not exists public.productos (
  id bigint generated by default as identity primary key,
  nombre text not null check (char_length(nombre) between 1 and 120),
  categoria text not null check (char_length(categoria) between 1 and 80),
  descripcion text not null default '',
  imagen text not null,
  precio numeric(12, 2) not null default 0 check (precio >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.citas (
  id bigint generated by default as identity primary key,
  nombre_cliente text not null,
  contacto text not null,
  fecha date not null,
  hora time not null,
  descripcion text not null,
  estado text not null default 'Pendiente' check (estado in ('Pendiente', 'En Preparación', 'Entregado')),
  precio numeric(12, 2) not null default 0 check (precio >= 0),
  tipo_pago text not null default 'Pendiente de Pago' check (tipo_pago in ('Pagado Completo', 'Mitad / Abono', 'Pendiente de Pago')),
  abono numeric(12, 2) not null default 0 check (abono >= 0 and abono <= precio),
  origen text not null default 'admin',
  items jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.productos add column if not exists precio numeric(12, 2) not null default 0 check (precio >= 0);
alter table public.citas add column if not exists items jsonb not null default '[]'::jsonb;

create table if not exists public.insumos (
  id bigint generated by default as identity primary key,
  ingrediente text not null unique check (char_length(ingrediente) between 1 and 120),
  stock_actual numeric(12, 3) not null default 0 check (stock_actual >= 0),
  unidad text not null default 'unidad' check (char_length(unidad) between 1 and 30),
  stock_minimo numeric(12, 3) not null default 1 check (stock_minimo >= 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.producto_insumos (
  producto_id bigint not null references public.productos(id) on delete cascade,
  insumo_id bigint not null references public.insumos(id) on delete cascade,
  cantidad numeric(12, 3) not null check (cantidad > 0),
  primary key (producto_id, insumo_id)
);

create table if not exists public.movimientos_inventario (
  id bigint generated by default as identity primary key,
  insumo_id bigint not null references public.insumos(id) on delete cascade,
  pedido_id bigint references public.citas(id) on delete set null,
  tipo text not null check (tipo in ('entrada', 'salida', 'ajuste', 'devolución')),
  cantidad numeric(12, 3) not null check (cantidad > 0),
  motivo text not null default '',
  created_at timestamptz not null default now()
);

create or replace function public.descontar_insumos_pedido()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  item jsonb;
  recipe record;
  required_stock numeric;
begin
  for item in select * from jsonb_array_elements(coalesce(new.items, '[]'::jsonb)) loop
    for recipe in select pi.insumo_id, pi.cantidad, i.stock_actual, i.ingrediente
      from producto_insumos pi join insumos i on i.id = pi.insumo_id
      where pi.producto_id = (item->>'id')::bigint loop
      required_stock := recipe.cantidad * greatest(1, (item->>'cantidad')::numeric);
      if recipe.stock_actual < required_stock then
        raise exception 'Stock insuficiente para %', recipe.ingrediente using errcode = 'check_violation';
      end if;
      update insumos set stock_actual = stock_actual - required_stock, updated_at = now() where id = recipe.insumo_id;
      insert into movimientos_inventario (insumo_id, pedido_id, tipo, cantidad, motivo)
      values (recipe.insumo_id, new.id, 'salida', required_stock, 'Pedido nuevo');
    end loop;
  end loop;
  return new;
end;
$$;

create or replace function public.reponer_insumos_pedido()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  item jsonb;
  recipe record;
  restored_stock numeric;
begin
  for item in select * from jsonb_array_elements(coalesce(old.items, '[]'::jsonb)) loop
    for recipe in select pi.insumo_id, pi.cantidad
      from producto_insumos pi
      where pi.producto_id = (item->>'id')::bigint loop
      restored_stock := recipe.cantidad * greatest(1, (item->>'cantidad')::numeric);
      update insumos set stock_actual = stock_actual + restored_stock, updated_at = now() where id = recipe.insumo_id;
      insert into movimientos_inventario (insumo_id, pedido_id, tipo, cantidad, motivo)
      values (recipe.insumo_id, old.id, 'devolución', restored_stock, 'Pedido eliminado');
    end loop;
  end loop;
  return old;
end;
$$;

drop trigger if exists descontar_insumos_al_crear_pedido on public.citas;
create trigger descontar_insumos_al_crear_pedido before insert on public.citas
for each row execute function public.descontar_insumos_pedido();

drop trigger if exists reponer_insumos_al_eliminar_pedido on public.citas;
create trigger reponer_insumos_al_eliminar_pedido
after delete on public.citas
for each row execute function public.reponer_insumos_pedido();

create index if not exists citas_fecha_estado_idx on public.citas (fecha, estado);
create index if not exists productos_categoria_idx on public.productos (categoria);
create index if not exists insumos_stock_idx on public.insumos (stock_actual, stock_minimo);
create index if not exists movimientos_inventario_insumo_idx on public.movimientos_inventario (insumo_id, created_at desc);

alter table public.productos enable row level security;
alter table public.citas enable row level security;
alter table public.insumos enable row level security;
alter table public.producto_insumos enable row level security;
alter table public.movimientos_inventario enable row level security;
drop policy if exists "catalogo público de productos" on public.productos;
drop policy if exists "servicio backend administra productos" on public.productos;
drop policy if exists "servicio backend administra pedidos" on public.citas;
drop policy if exists "servicio backend administra insumos" on public.insumos;
drop policy if exists "servicio backend administra recetas" on public.producto_insumos;
drop policy if exists "servicio backend administra movimientos" on public.movimientos_inventario;
create policy "catalogo público de productos" on public.productos for select using (true);
create policy "servicio backend administra productos" on public.productos for all using (false) with check (false);
create policy "servicio backend administra pedidos" on public.citas for all using (false) with check (false);
create policy "servicio backend administra insumos" on public.insumos for all using (false) with check (false);
create policy "servicio backend administra recetas" on public.producto_insumos for all using (false) with check (false);
create policy "servicio backend administra movimientos" on public.movimientos_inventario for all using (false) with check (false);

insert into storage.buckets (id, name, public) values ('productos', 'productos', true) on conflict (id) do nothing;
