create table if not exists public.productos (
  id bigint generated by default as identity primary key,
  nombre text not null check (char_length(nombre) between 1 and 120),
  categoria text not null check (char_length(categoria) between 1 and 80),
  descripcion text not null default '',
  imagen text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.citas (
  id bigint generated by default as identity primary key,
  nombre_cliente text not null,
  contacto text not null,
  fecha date not null,
  hora time not null,
  descripcion text not null,
  estado text not null default 'Pendiente' check (estado in ('Pendiente', 'En Preparación', 'Entregado')),
  precio numeric(12, 2) not null default 0 check (precio >= 0),
  tipo_pago text not null default 'Pendiente de Pago' check (tipo_pago in ('Pagado Completo', 'Mitad / Abono', 'Pendiente de Pago')),
  abono numeric(12, 2) not null default 0 check (abono >= 0 and abono <= precio),
  origen text not null default 'admin',
  created_at timestamptz not null default now()
);

create index if not exists citas_fecha_estado_idx on public.citas (fecha, estado);
create index if not exists productos_categoria_idx on public.productos (categoria);

alter table public.productos enable row level security;
alter table public.citas enable row level security;
create policy "catalogo público de productos" on public.productos for select using (true);
create policy "servicio backend administra productos" on public.productos for all using (false) with check (false);
create policy "servicio backend administra pedidos" on public.citas for all using (false) with check (false);

insert into storage.buckets (id, name, public) values ('productos', 'productos', true) on conflict (id) do nothing;
