create table if not exists public.productos (
  id bigint generated by default as identity primary key,
  nombre text not null check (char_length(nombre) between 1 and 120),
  categoria text not null check (char_length(categoria) between 1 and 80),
  descripcion text not null default '',
  imagen text not null,
  precio numeric(12, 2) not null default 0 check (precio >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.citas (
  id bigint generated by default as identity primary key,
  nombre_cliente text not null,
  contacto text not null,
  fecha date not null,
  hora time not null,
  descripcion text not null,
  estado text not null default 'Pendiente' check (estado in ('Pendiente', 'En Preparación', 'Entregado')),
  precio numeric(12, 2) not null default 0 check (precio >= 0),
  tipo_pago text not null default 'Pendiente de Pago' check (tipo_pago in ('Pagado Completo', 'Mitad / Abono', 'Pendiente de Pago')),
  abono numeric(12, 2) not null default 0 check (abono >= 0 and abono <= precio),
  origen text not null default 'admin',
  items jsonb not null default '[]'::jsonb,
  archived_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.productos add column if not exists precio numeric(12, 2) not null default 0 check (precio >= 0);
alter table public.productos add column if not exists destacado boolean not null default false;
alter table public.productos add column if not exists disponible boolean not null default true;
alter table public.productos add column if not exists descuento_porcentaje numeric(5, 2) not null default 0 check (descuento_porcentaje between 0 and 100);
alter table public.citas add column if not exists items jsonb not null default '[]'::jsonb;

create table if not exists public.insumos (
  id bigint generated by default as identity primary key,
  ingrediente text not null unique check (char_length(ingrediente) between 1 and 120),
  stock_actual numeric(12, 3) not null default 0 check (stock_actual >= 0),
  unidad text not null default 'unidad' check (char_length(unidad) between 1 and 30),
  stock_minimo numeric(12, 3) not null default 1 check (stock_minimo >= 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.producto_insumos (
  producto_id bigint not null references public.productos(id) on delete cascade,
  insumo_id bigint not null references public.insumos(id) on delete cascade,
  cantidad numeric(12, 3) not null check (cantidad > 0),
  primary key (producto_id, insumo_id)
);

create table if not exists public.movimientos_inventario (
  id bigint generated by default as identity primary key,
  insumo_id bigint not null references public.insumos(id) on delete cascade,
  pedido_id bigint references public.citas(id) on delete set null,
  tipo text not null check (tipo in ('entrada', 'salida', 'ajuste', 'devolución')),
  cantidad numeric(12, 3) not null check (cantidad > 0),
  motivo text not null default '',
  created_at timestamptz not null default now()
);

create or replace function public.descontar_insumos_pedido()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  item jsonb;
  recipe record;
  required_stock numeric;
begin
  for item in select * from jsonb_array_elements(coalesce(new.items, '[]'::jsonb)) loop
    for recipe in select pi.insumo_id, pi.cantidad, i.stock_actual, i.ingrediente
      from producto_insumos pi join insumos i on i.id = pi.insumo_id
      where pi.producto_id = (item->>'id')::bigint loop
      required_stock := recipe.cantidad * greatest(1, (item->>'cantidad')::numeric);
      if recipe.stock_actual < required_stock then
        raise exception 'Stock insuficiente para %', recipe.ingrediente using errcode = 'check_violation';
      end if;
      update insumos set stock_actual = stock_actual - required_stock, updated_at = now() where id = recipe.insumo_id;
      insert into movimientos_inventario (insumo_id, pedido_id, tipo, cantidad, motivo)
      values (recipe.insumo_id, new.id, 'salida', required_stock, 'Pedido nuevo');
    end loop;
  end loop;
  return new;
end;
$$;

create or replace function public.reponer_insumos_pedido()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  item jsonb;
  recipe record;
  restored_stock numeric;
begin
  for item in select * from jsonb_array_elements(coalesce(old.items, '[]'::jsonb)) loop
    for recipe in select pi.insumo_id, pi.cantidad
      from producto_insumos pi
      where pi.producto_id = (item->>'id')::bigint loop
      restored_stock := recipe.cantidad * greatest(1, (item->>'cantidad')::numeric);
      update insumos set stock_actual = stock_actual + restored_stock, updated_at = now() where id = recipe.insumo_id;
      insert into movimientos_inventario (insumo_id, pedido_id, tipo, cantidad, motivo)
      values (recipe.insumo_id, old.id, 'devolución', restored_stock, 'Pedido eliminado');
    end loop;
  end loop;
  return old;
end;
$$;

drop trigger if exists descontar_insumos_al_crear_pedido on public.citas;
create trigger descontar_insumos_al_crear_pedido before insert on public.citas
for each row execute function public.descontar_insumos_pedido();

drop trigger if exists reponer_insumos_al_eliminar_pedido on public.citas;
create trigger reponer_insumos_al_eliminar_pedido
before delete on public.citas
for each row execute function public.reponer_insumos_pedido();

create index if not exists citas_fecha_estado_idx on public.citas (fecha, estado);
create index if not exists productos_categoria_idx on public.productos (categoria);
create index if not exists insumos_stock_idx on public.insumos (stock_actual, stock_minimo);
create index if not exists movimientos_inventario_insumo_idx on public.movimientos_inventario (insumo_id, created_at desc);

alter table public.productos enable row level security;
alter table public.citas enable row level security;
alter table public.insumos enable row level security;
alter table public.producto_insumos enable row level security;
alter table public.movimientos_inventario enable row level security;
drop policy if exists "catalogo público de productos" on public.productos;
drop policy if exists "servicio backend administra productos" on public.productos;
drop policy if exists "servicio backend administra pedidos" on public.citas;
drop policy if exists "servicio backend administra insumos" on public.insumos;
drop policy if exists "servicio backend administra recetas" on public.producto_insumos;
drop policy if exists "servicio backend administra movimientos" on public.movimientos_inventario;
create policy "catalogo público de productos" on public.productos for select using (true);
create policy "servicio backend administra productos" on public.productos for all using (false) with check (false);
create policy "servicio backend administra pedidos" on public.citas for all using (false) with check (false);
create policy "servicio backend administra insumos" on public.insumos for all using (false) with check (false);
create policy "servicio backend administra recetas" on public.producto_insumos for all using (false) with check (false);
create policy "servicio backend administra movimientos" on public.movimientos_inventario for all using (false) with check (false);

alter table public.insumos add column if not exists costo_unitario numeric(12, 2) not null default 0 check (costo_unitario >= 0);
alter table public.insumos add column if not exists fecha_vencimiento date;
alter table public.citas add column if not exists confirmada_at timestamptz;
alter table public.citas add column if not exists entregada_at timestamptz;
alter table public.citas add column if not exists reprogramada_at timestamptz;
alter table public.citas add column if not exists notas_internas text not null default '';
alter table public.citas add column if not exists personalizacion jsonb not null default '{}'::jsonb;
alter table public.citas add column if not exists checklist jsonb not null default '[]'::jsonb;
alter table public.citas add column if not exists tracking_token uuid not null default gen_random_uuid();
alter table public.citas add column if not exists updated_at timestamptz not null default now();

alter table public.citas drop constraint if exists citas_estado_check;
alter table public.citas add constraint citas_estado_check check (estado in ('Pendiente', 'Confirmado', 'En producción', 'Listo', 'Entregado', 'Cancelado'));

create table if not exists public.perfiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nombre text not null default '',
  rol text not null default 'solo_lectura' check (rol in ('administrador', 'produccion', 'ventas', 'solo_lectura')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.crear_perfil_auth()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.perfiles (id, nombre)
  values (new.id, coalesce(new.raw_user_meta_data->>'name', new.email, 'Usuario'))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists crear_perfil_al_registrar_usuario on auth.users;
create trigger crear_perfil_al_registrar_usuario
after insert on auth.users
for each row execute function public.crear_perfil_auth();

create table if not exists public.pedido_historial (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null references public.citas(id) on delete cascade,
  usuario_id uuid references auth.users(id) on delete set null,
  estado_anterior text,
  estado_nuevo text not null,
  notas text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.gastos (
  id bigint generated by default as identity primary key,
  concepto text not null,
  categoria text not null default 'operativo',
  monto numeric(12, 2) not null check (monto >= 0),
  fecha date not null default current_date,
  notas text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.variantes_producto (
  id bigint generated by default as identity primary key,
  producto_id bigint not null references public.productos(id) on delete cascade,
  nombre text not null,
  precio numeric(12, 2) not null check (precio >= 0),
  disponible boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.adicionales (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  precio numeric(12, 2) not null check (precio >= 0),
  disponible boolean not null default true
);

create table if not exists public.pedido_mensajes (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null references public.citas(id) on delete cascade,
  canal text not null check (canal in ('whatsapp', 'email', 'sms')),
  plantilla text not null,
  proveedor_id text not null default '',
  estado text not null default 'pendiente' check (estado in ('pendiente', 'enviado', 'fallido')),
  error text not null default '',
  enviado_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.resenas (
  id bigint generated by default as identity primary key,
  pedido_id bigint references public.citas(id) on delete set null,
  nombre text not null default 'Cliente',
  puntuacion integer not null check (puntuacion between 1 and 5),
  comentario text not null default '',
  publicada boolean not null default false,
  created_at timestamptz not null default now()
);

create or replace function public.registrar_cambio_pedido()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  new.updated_at := now();
  if tg_op = 'INSERT' then
    insert into pedido_historial (pedido_id, usuario_id, estado_anterior, estado_nuevo, notas)
    values (new.id, auth.uid(), null, new.estado, new.notas_internas);
  elsif old.estado is distinct from new.estado then
    insert into pedido_historial (pedido_id, usuario_id, estado_anterior, estado_nuevo, notas)
    values (new.id, auth.uid(), old.estado, new.estado, new.notas_internas);
  end if;
  if new.estado = 'Confirmado' and (tg_op = 'INSERT' or old.estado is distinct from new.estado) then new.confirmada_at := now(); end if;
  if new.estado = 'Entregado' and (tg_op = 'INSERT' or old.estado is distinct from new.estado) then new.entregada_at := now(); end if;
  return new;
end;
$$;

drop trigger if exists registrar_cambio_pedido on public.citas;
create trigger registrar_cambio_pedido before update on public.citas
for each row execute function public.registrar_cambio_pedido();

create or replace function public.registrar_pedido_nuevo()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into pedido_historial (pedido_id, usuario_id, estado_anterior, estado_nuevo, notas)
  values (new.id, auth.uid(), null, new.estado, new.notas_internas);
  return new;
end;
$$;

drop trigger if exists registrar_pedido_nuevo on public.citas;
create trigger registrar_pedido_nuevo after insert on public.citas
for each row execute function public.registrar_pedido_nuevo();

create index if not exists citas_tracking_token_idx on public.citas (tracking_token);
create index if not exists citas_estado_fecha_idx on public.citas (estado, fecha);
create index if not exists gastos_fecha_idx on public.gastos (fecha);
create index if not exists pedido_historial_pedido_idx on public.pedido_historial (pedido_id, created_at desc);

alter table public.perfiles enable row level security;
alter table public.pedido_historial enable row level security;
alter table public.gastos enable row level security;
alter table public.variantes_producto enable row level security;
alter table public.adicionales enable row level security;
alter table public.pedido_mensajes enable row level security;
alter table public.resenas enable row level security;

drop policy if exists "usuarios leen su perfil" on public.perfiles;
create policy "usuarios leen su perfil" on public.perfiles for select using (auth.uid() = id);
drop policy if exists "catalogo público variantes" on public.variantes_producto;
create policy "catalogo público variantes" on public.variantes_producto for select using (disponible = true);
drop policy if exists "catalogo público adicionales" on public.adicionales;
create policy "catalogo público adicionales" on public.adicionales for select using (disponible = true);
drop policy if exists "resenas publicadas" on public.resenas;
create policy "resenas publicadas" on public.resenas for select using (publicada = true);

insert into storage.buckets (id, name, public) values ('productos', 'productos', true) on conflict (id) do nothing;
