-- Ejecutar en Supabase SQL Editor antes de usar estados, inventario y finanzas.
-- Es idempotente y puede ejecutarse más de una vez.

alter table public.citas add column if not exists notas_internas text not null default '';
alter table public.citas add column if not exists updated_at timestamptz not null default now();
alter table public.citas add column if not exists tracking_token uuid not null default gen_random_uuid();
alter table public.citas add column if not exists archived_at timestamptz;

update public.citas
set estado = 'En producción'
where estado = 'En Preparación';

alter table public.citas drop constraint if exists citas_estado_check;
alter table public.citas add constraint citas_estado_check
  check (estado in ('Pendiente', 'Confirmado', 'En producción', 'Listo', 'Entregado', 'Cancelado));

create table if not exists public.movimientos_inventario (
  id bigint generated by default as identity primary key,
  insumo_id bigint not null references public.insumos(id) on delete cascade,
  pedido_id bigint references public.citas(id) on delete set null,
  tipo text not null check (tipo in ('entrada', 'salida', 'ajuste', 'devolución')),
  cantidad numeric(12, 3) not null check (cantidad > 0),
  motivo text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.gastos (
  id bigint generated by default as identity primary key,
  concepto text not null,
  categoria text not null default 'operativo',
  monto numeric(12, 2) not null check (monto >= 0),
  fecha date not null default current_date,
  notas text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.pedido_historial (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null references public.citas(id) on delete cascade,
  usuario_id uuid references auth.users(id) on delete set null,
  estado_anterior text,
  estado_nuevo text not null,
  notas text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.pedido_mensajes (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null references public.citas(id) on delete cascade,
  canal text not null check (canal in ('whatsapp', 'email', 'sms')),
  plantilla text not null,
  proveedor_id text not null default '',
  estado text not null default 'pendiente' check (estado in ('pendiente', 'enviado', 'fallido')),
  error text not null default '',
  enviado_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists movimientos_inventario_insumo_idx
  on public.movimientos_inventario (insumo_id, created_at desc);
create index if not exists pedido_historial_pedido_idx
  on public.pedido_historial (pedido_id, created_at desc);
create index if not exists gastos_fecha_idx on public.gastos (fecha);
create index if not exists citas_tracking_token_idx on public.citas (tracking_token);
create index if not exists citas_archived_at_idx on public.citas (archived_at);

create or replace function public.registrar_cambio_pedido()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  new.updated_at := now();
  if tg_op = 'INSERT' then
    insert into public.pedido_historial (pedido_id, usuario_id, estado_anterior, estado_nuevo, notas)
    values (new.id, auth.uid(), null, new.estado, new.notas_internas);
  elsif old.estado is distinct from new.estado then
    insert into public.pedido_historial (pedido_id, usuario_id, estado_anterior, estado_nuevo, notas)
    values (new.id, auth.uid(), old.estado, new.estado, new.notas_internas);
  end if;
  return new;
end;
$$;

drop trigger if exists registrar_cambio_pedido on public.citas;
create trigger registrar_cambio_pedido
before insert or update on public.citas
for each row execute function public.registrar_cambio_pedido();

alter table public.movimientos_inventario enable row level security;
alter table public.gastos enable row level security;
alter table public.pedido_historial enable row level security;
alter table public.pedido_mensajes enable row level security;

-- El backend usa la clave service role; el navegador no obtiene acceso directo.
